import asyncio
import logging
import os
import tempfile
from io import BytesIO
import base64

import torch
import cv2
import numpy as np
from PIL import Image
from torchvision.models import efficientnet_b0
from torchvision import transforms
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes
import google.generativeai as genai

# Bot token
TOKEN = "5614405588:AAEtmjQNR8cppePAxUxRIlcYzDOK4Y11ghc"

# Gemini API
GEMINI_API_KEY = "AIzaSyAbkpCTBDcTqBdY-aF6Qbo7wPwd8Rw4KNU"
genai.configure(api_key=GEMINI_API_KEY)

# Initialize Gemini model
gemini_model = genai.GenerativeModel('gemini-1.5-flash')

# Setup logging
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)
logger = logging.getLogger(__name__)

# Load model


def load_model():
    model = efficientnet_b0()
    model.classifier[1] = torch.nn.Linear(model.classifier[1].in_features, 2)
    model_path = "models/best_model-v3.pt"
    if not os.path.exists(model_path):
        model_path = "/models/best_model-v3.pt"
    model.load_state_dict(torch.load(model_path, map_location="cpu"))
    model.eval()
    return model


model = load_model()

# Preprocessing
preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "🧠 *Deepfake Detector Bot*\n\n"
        "Send me an image or video and I'll analyze if it's real or fake.\n\n"
        "Commands:\n"
        "/start - Start the bot\n"
        "/help - How to use",
        parse_mode='Markdown'
    )


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "📸 *Send any image or video*\n\n"
        "I'll analyze it using EfficientNet-B0 and tell you if it's:\n"
        "✅ Real\n"
        "❌ Deepfake\n\n"
        "Supported formats: JPG, PNG, MP4, MOV",
        parse_mode='Markdown'
    )


def detect_watermark(image_path):
    """
    Detect common AI/deepfake watermarks in image
    Returns: (has_watermark, watermark_text)
    """
    try:
        img = cv2.imread(image_path)
        if img is None:
            return False, ""

        # Common watermarks to detect
        watermark_keywords = [
            "deepfake", "deep fake", "ai generated", "ai-generated",
            "midjourney", "dall-e", "dalle", "stable diffusion",
            "synthetic", "fake", "generated by ai", "made with ai",
            "this is fake", "not real", "artificial"
        ]

        # Use Gemini to check for watermarks
        with open(image_path, 'rb') as f:
            image_data = f.read()

        prompt = """
        Look at this image carefully. Check if there is ANY text watermark visible,
        especially at corners, bottom, or any overlay text.
        
        Common watermarks: "Deepfake", "AI Generated", "Midjourney", "DALL-E", 
        "Stable Diffusion", "Fake", "Synthetic", etc.
        
        Respond with ONLY a JSON object:
        {"has_watermark": true/false, "watermark_text": "detected text or empty"}
        """

        response = gemini_model.generate_content(
            [prompt, {"mime_type": "image/jpeg", "data": image_data}]
        )

        try:
            import json
            result_text = response.text.strip()
            if "```json" in result_text:
                result_text = result_text.split("```json")[1].split("```")[0]
            elif "```" in result_text:
                result_text = result_text.split("```")[1].split("```")[0]

            result = json.loads(result_text.strip())
            has_wm = result.get("has_watermark", False)
            wm_text = result.get("watermark_text", "").lower()

            # Double check with keyword matching
            if not has_wm and wm_text:
                for keyword in watermark_keywords:
                    if keyword in wm_text:
                        has_wm = True
                        break

            return has_wm, wm_text
        except:
            return False, ""
    except Exception as e:
        return False, ""


def analyze_with_gemini(image_path):
    """
    Use Gemini Vision API to analyze image for deepfake indicators
    """
    try:
        # Load and encode image
        with open(image_path, 'rb') as f:
            image_data = f.read()

        # Create prompt for Gemini
        prompt = """
        Analyze this image for signs of being AI-generated or manipulated (deepfake).
        Look for:
        1. Unnatural skin textures or smoothing
        2. Inconsistent lighting on face
        3. Weird eyes, teeth, or hair
        4. Blurry or distorted background
        5. Unnatural facial proportions
        
        Respond with ONLY a JSON object in this format:
        {"is_fake": true/false, "confidence": 0-100, "indicators": ["list", "of", "issues"]}
        """

        # Generate response
        response = gemini_model.generate_content(
            [prompt, {"mime_type": "image/jpeg", "data": image_data}]
        )

        # Parse response
        try:
            import json
            result_text = response.text.strip()
            # Extract JSON if wrapped in markdown
            if "```json" in result_text:
                result_text = result_text.split("```json")[1].split("```")[0]
            elif "```" in result_text:
                result_text = result_text.split("```")[1].split("```")[0]

            result = json.loads(result_text.strip())
            return {
                "is_fake": result.get("is_fake", False),
                "confidence": result.get("confidence", 50),
                "indicators": result.get("indicators", [])
            }
        except:
            return {"is_fake": False, "confidence": 50, "indicators": ["Analysis error"]}
    except Exception as e:
        return {"is_fake": False, "confidence": 50, "indicators": [f"Error: {str(e)}"]}


def detect_face_swap_opencv(image_path):
    """
    Face swap detection using OpenCV:
    1. Face detection quality
    2. Edge artifacts around face
    3. Color consistency
    """
    try:
        img = cv2.imread(image_path)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # Load classifiers
        face_cascade = cv2.CascadeClassifier(
            cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

        # Detect faces
        faces = face_cascade.detectMultiScale(gray, 1.1, 4)
        face_count = len(faces)

        if face_count == 0:
            return {"face_count": 0, "suspicious": False, "details": "No face detected"}

        suspicious_indicators = []

        for (x, y, w, h) in faces:
            # Extract face region
            face_roi = img[y:y+h, x:x+w]
            face_gray = gray[y:y+h, x:x+w]

            # Check 1: Face edge sharpness (swapped faces often have blur at edges)
            edges = cv2.Canny(face_gray, 100, 200)
            edge_ratio = np.sum(edges > 0) / (w * h)
            if edge_ratio < 0.05:
                suspicious_indicators.append("unnatural_face_edges")

            # Check 2: Color consistency in face vs background
            face_mean = np.mean(face_roi, axis=(0, 1))
            bg_roi = img[max(0, y-20):y, max(0, x-20):x+w+20]
            if bg_roi.size > 0:
                bg_mean = np.mean(bg_roi, axis=(0, 1))
                color_diff = np.abs(face_mean - bg_mean)
                if np.mean(color_diff) > 60:
                    suspicious_indicators.append("color_mismatch")

            # Check 3: Face aspect ratio (unnatural proportions)
            aspect_ratio = w / h
            if aspect_ratio < 0.7 or aspect_ratio > 0.95:
                suspicious_indicators.append("unnatural_proportions")

        is_suspicious = len(suspicious_indicators) >= 2

        return {
            "face_count": face_count,
            "suspicious": is_suspicious,
            "indicators": suspicious_indicators,
            "details": ", ".join(suspicious_indicators) if suspicious_indicators else "Normal"
        }
    except Exception as e:
        return {"face_count": 0, "suspicious": False, "details": f"Error: {str(e)}"}


def analyze_image(image_path):
    """Analyze image for deepfake detection with multi-layer approach + Gemini + Watermark"""

    # Layer 0: Watermark detection (highest priority)
    has_watermark, watermark_text = detect_watermark(image_path)
    if has_watermark:
        return "WATERMARKED FAKE ❌", 95.0, 0, f"Watermark detected: '{watermark_text}'"

    img = Image.open(image_path).convert("RGB")
    tensor = preprocess(img).unsqueeze(0)

    # Layer 1: Model prediction
    with torch.no_grad():
        out = model(tensor)
        probs = torch.softmax(out, dim=1)[0]
        conf, pred = torch.max(probs, dim=0)

    model_confidence = conf.item()
    model_label = "FAKE" if pred.item() == 1 else "REAL"

    # Layer 2: Face swap detection
    face_analysis = detect_face_swap_opencv(image_path)

    # Layer 3: Gemini AI analysis
    gemini_result = analyze_with_gemini(image_path)
    gemini_fake = gemini_result["is_fake"]
    gemini_conf = gemini_result["confidence"] / 100.0
    gemini_indicators = gemini_result["indicators"]

    # Multi-layer decision with Gemini
    if model_confidence > 0.85 and model_label == "FAKE":
        final_label = "DEEPFAKE ❌"
        reason = "High confidence AI detection"
    elif gemini_fake and gemini_conf > 0.7:
        final_label = "AI-GENERATED ❌"
        reason = f"Gemini detected: {', '.join(gemini_indicators[:3])}"
    elif face_analysis["suspicious"] and model_label == "FAKE":
        final_label = "FACE SWAP ❌"
        reason = f"Face swap detected: {face_analysis['details']}"
    elif model_confidence > 0.7 and model_label == "FAKE":
        final_label = "SUSPICIOUS ⚠️"
        reason = "Possible manipulation"
    elif face_analysis["suspicious"]:
        final_label = "SUSPICIOUS ⚠️"
        reason = f"Anomalies: {face_analysis['details']}"
    elif gemini_fake:
        final_label = "SUSPICIOUS ⚠️"
        reason = f"Gemini flags: {', '.join(gemini_indicators[:2])}"
    else:
        final_label = "REAL ✅"
        reason = "No manipulation detected"

    confidence = model_confidence * 100

    return final_label, confidence, face_analysis["face_count"], reason


def analyze_video(video_path):
    """Analyze first frame of video"""
    cap = cv2.VideoCapture(video_path)
    ret, frame = cap.read()
    cap.release()

    if not ret:
        return "Error reading video", 0

    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    img = Image.fromarray(frame)
    tensor = preprocess(img).unsqueeze(0)

    with torch.no_grad():
        out = model(tensor)
        probs = torch.softmax(out, dim=1)[0]
        conf, pred = torch.max(probs, dim=0)

    is_real = pred.item() == 0
    label = "REAL ✅ (1st frame)" if is_real else "DEEPFAKE ❌ (1st frame)"
    confidence = conf.item() * 100

    return label, confidence


async def handle_photo(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle image uploads"""
    await update.message.reply_text("🔍 Analyzing image...")

    # Get photo
    photo = update.message.photo[-1]  # Get highest quality
    file = await context.bot.get_file(photo.file_id)

    # Download to temp file
    with tempfile.NamedTemporaryFile(suffix='.jpg', delete=False) as tmp:
        await file.download_to_drive(tmp.name)
        tmp_path = tmp.name

    try:
        # Analyze with multi-layer detection
        label, confidence, face_count, reason = analyze_image(tmp_path)

        # Send result
        result_text = (
            f"🧠 *Analysis Result*\n\n"
            f"📊 Prediction: *{label}*\n"
            f"🎯 Confidence: *{confidence:.1f}%*\n"
            f"👤 Faces: *{face_count}*\n"
            f"📝 Reason: {reason}\n\n"
            f"Multi-layer: EfficientNet + Face Analysis"
        )
        await update.message.reply_text(result_text, parse_mode='Markdown')

    finally:
        os.unlink(tmp_path)


async def handle_video(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle video uploads"""
    await update.message.reply_text("🔍 Analyzing video (first frame)...")

    # Get video
    video = update.message.video or update.message.document
    file = await context.bot.get_file(video.file_id)

    # Download to temp file
    with tempfile.NamedTemporaryFile(suffix='.mp4', delete=False) as tmp:
        await file.download_to_drive(tmp.name)
        tmp_path = tmp.name

    try:
        # Analyze
        label, confidence = analyze_video(tmp_path)

        # Send result
        result_text = (
            f"🧠 *Video Analysis*\n\n"
            f"📊 Prediction: *{label}*\n"
            f"🎯 Confidence: *{confidence:.1f}%*\n\n"
            f"⚠️ Note: Only first frame analyzed\n"
            f"Powered by EfficientNet-B0"
        )
        await update.message.reply_text(result_text, parse_mode='Markdown')

    finally:
        os.unlink(tmp_path)


async def handle_document(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle document uploads (images/videos as documents)"""
    doc = update.message.document
    mime_type = doc.mime_type or ""

    if mime_type.startswith("image"):
        await update.message.reply_text("🔍 Analyzing image...")

        file = await context.bot.get_file(doc.file_id)
        ext = ".jpg" if "jpeg" in mime_type else ".png"

        with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp:
            await file.download_to_drive(tmp.name)
            tmp_path = tmp.name

        try:
            label, confidence = analyze_image(tmp_path)
            result_text = (
                f"🧠 *Analysis Result*\n\n"
                f"📊 Prediction: *{label}*\n"
                f"🎯 Confidence: *{confidence:.1f}%*\n\n"
                f"Powered by EfficientNet-B0"
            )
            await update.message.reply_text(result_text, parse_mode='Markdown')
        finally:
            os.unlink(tmp_path)

    elif mime_type.startswith("video"):
        await handle_video(update, context)
    else:
        await update.message.reply_text("❌ Unsupported file type. Send images (JPG, PNG) or videos (MP4).")


async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    logger.error(f"Update {update} caused error {context.error}")
    if update and update.message:
        await update.message.reply_text("❌ An error occurred. Please try again.")


def main():
    # Create application
    application = Application.builder().token(TOKEN).build()

    # Add handlers
    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("help", help_command))
    application.add_handler(MessageHandler(filters.PHOTO, handle_photo))
    application.add_handler(MessageHandler(filters.VIDEO, handle_video))
    application.add_handler(MessageHandler(
        filters.Document.ALL, handle_document))
    application.add_error_handler(error_handler)

    # Run
    logger.info("Bot started!")
    application.run_polling()


if __name__ == "__main__":
    main()
